In [47]:
import pandas as pd

In [48]:
# Import the data
data = pd.read_csv('Subset 3 - 2022_2023 PSES open dataset - with labels_Sous-ensemble 3 - Ensemble de données ouvertes du SAFF de 2022_23.csv', encoding='latin-1')

In [49]:
data.shape

(471994, 35)

In [50]:
# show head of the data, and show all the columns
pd.set_option('display.max_columns', None)
data.head()

,LEVEL1ID,LEVEL2ID,LEVEL3ID,LEVEL4ID,LEVEL5ID,SURVEYR,BYCOND,descrip_E,descrip_F,DEMCODE,QUESTION,TITLE_E,TITLE_F,ANSWER1,ANSWER2,ANSWER3,ANSWER4,ANSWER5,ANSWER6,ANSWER7,MOST_POSITIVE_OR_LEAST_NEGATIVE,NEUTRAL_OR_MIDDLE_CATEGORY,MOST_NEGATIVE_OR_LEAST_POSITIVE,AGREE,SCORE5,SCORE100,ANSCOUNT,DEPT_E,DEPT_F,INDICATORID,INDICATORENG,INDICATORFRA,SUBINDICATORID,SUBINDICATORENG,SUBINDICATORFRA
0,0,0,0,0,0,2022,Q117 = 1,Man,Homme,1087,Q01,"Question 1. I have the tools, technology and e...","Question 1. Je dispose des outils, de la techn...",39,42,5,9,5,0,0,81,5,14,81,4.02,76,69605.0,Public Service,Fonction publique,4.0,Workplace,Milieu de travail,14.0,Physical environment and equipment,Environnement physique et équipement
1,1,0,0,0,0,2022,Q117 = 1,Man,Homme,1087,Q01,"Question 1. I have the tools, technology and e...","Question 1. Je dispose des outils, de la techn...",53,37,3,5,2,0,0,91,3,6,91,4.36,84,13060.0,Canada Revenue Agency,Agence du revenu du Canada,4.0,Workplace,Milieu de travail,14.0,Physical environment and equipment,Environnement physique et équipement
2,2,0,0,0,0,2022,Q117 = 1,Man,Homme,1087,Q01,"Question 1. I have the tools, technology and e...","Question 1. Je dispose des outils, de la techn...",51,37,3,6,3,0,0,88,3,9,88,4.27,82,6090.0,Employment and Social Development Canada,Emploi et Développement social Canada,4.0,Workplace,Milieu de travail,14.0,Physical environment and equipment,Environnement physique et équipement
3,3,0,0,0,0,2022,Q117 = 1,Man,Homme,1087,Q01,"Question 1. I have the tools, technology and e...","Question 1. Je dispose des outils, de la techn...",28,45,6,13,7,0,0,73,6,21,73,3.73,68,6330.0,Department of National Defence,Ministère de la Défense nationale,4.0,Workplace,Milieu de travail,14.0,Physical environment and equipment,Environnement physique et équipement
4,4,0,0,0,0,2022,Q117 = 1,Man,Homme,1087,Q01,"Question 1. I have the tools, technology and e...","Question 1. Je dispose des outils, de la techn...",17,45,7,17,13,0,0,63,7,30,63,3.36,59,2310.0,Correctional Service Canada,Service correctionnel Canada,4.0,Workplace,Milieu de travail,14.0,Physical environment and equipment,Environnement physique et équipement

In [51]:
data.tail()

,LEVEL1ID,LEVEL2ID,LEVEL3ID,LEVEL4ID,LEVEL5ID,SURVEYR,BYCOND,descrip_E,descrip_F,DEMCODE,QUESTION,TITLE_E,TITLE_F,ANSWER1,ANSWER2,ANSWER3,ANSWER4,ANSWER5,ANSWER6,ANSWER7,MOST_POSITIVE_OR_LEAST_NEGATIVE,NEUTRAL_OR_MIDDLE_CATEGORY,MOST_NEGATIVE_OR_LEAST_POSITIVE,AGREE,SCORE5,SCORE100,ANSCOUNT,DEPT_E,DEPT_F,INDICATORID,INDICATORENG,INDICATORFRA,SUBINDICATORID,SUBINDICATORENG,SUBINDICATORFRA
471989,31,0,0,0,0,2022,D122G = 1,2SLGBTQIA+: Questioning,2ELGBTQIA+ : En questionnement,1158,Q55,Question 55. I would prefer to remain with my ...,Question 55. Je préférerais continuer à travai...,X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Canadian Radio-television and Telecommunicatio...,Conseil de la radiodiffusion et des télécommun...,1.0,Employee engagement,Mobilisation des employés,1.0,Employee engagement,Mobilisation des employés
471990,35,0,0,0,0,2022,D122G = 1,2SLGBTQIA+: Questioning,2ELGBTQIA+ : En questionnement,1158,Q55,Question 55. I would prefer to remain with my ...,Question 55. Je préférerais continuer à travai...,X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Canadian Institutes of Health Research,Instituts de recherche en santé du Canada,1.0,Employee engagement,Mobilisation des employés,1.0,Employee engagement,Mobilisation des employés
471991,36,0,0,0,0,2022,D122G = 1,2SLGBTQIA+: Questioning,2ELGBTQIA+ : En questionnement,1158,Q55,Question 55. I would prefer to remain with my ...,Question 55. Je préférerais continuer à travai...,X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Parole Board of Canada,Commission des libérations conditionnelles du ...,1.0,Employee engagement,Mobilisation des employés,1.0,Employee engagement,Mobilisation des employés
471992,37,0,0,0,0,2022,D122G = 1,2SLGBTQIA+: Questioning,2ELGBTQIA+ : En questionnement,1158,Q55,Question 55. I would prefer to remain with my ...,Question 55. Je préférerais continuer à travai...,X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Shared Services Canada,Services partagés Canada,1.0,Employee engagement,Mobilisation des employés,1.0,Employee engagement,Mobilisation des employés
471993,39,0,0,0,0,2022,D122G = 1,2SLGBTQIA+: Questioning,2ELGBTQIA+ : En questionnement,1158,Q55,Question 55. I would prefer to remain with my ...,Question 55. Je préférerais continuer à travai...,X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Transportation,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 471994 entries, 0 to 471993
Data columns (total 35 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   LEVEL1ID                         471994 non-null  int64
 1   LEVEL2ID                         471994 non-null  int64
 2   LEVEL3ID                         471994 non-null  int64
 3   LEVEL4ID                         471994 non-null  int64
 4   LEVEL5ID                         471994 non-null  int64
 5   SURVEYR                          471994 non-null  int64
 6   BYCOND                           471994 non-null  object
 7   descrip_E                        471994 non-null  object
 8   descrip_F                        471994 non-null  object
 9   DEMCODE                          471994 non-null  int64
 10  QUESTION                         471994 non-null  object
 11  TITLE_E                          471994 non-null  object
 12  TITLE_F                          471994 non-null  object
 13  ANSWER1                          417655 non-null  object
 14  ANSWER2                          417655 non-null  object
 15  ANSWER3                          417655 non-null  object
 16  ANSWER4                          417655 non-null  object
 17  ANSWER5                          417655 non-null  object
 18  ANSWER6                          417655 non-null  object
 19  ANSWER7                          417655 non-null  object
 20  MOST_POSITIVE_OR_LEAST_NEGATIVE  417655 non-null  object
 21  NEUTRAL_OR_MIDDLE_CATEGORY       417655 non-null  object
 22  MOST_NEGATIVE_OR_LEAST_POSITIVE  417655 non-null  object
 23  AGREE                            417655 non-null  object
 24  SCORE5                           417655 non-null  object
 25  SCORE100                         417655 non-null  object
 26  ANSCOUNT                         306624 non-null  float64
 27  DEPT_E                           471994 non-null  object
 28  DEPT_F                           471993 non-null  object
 29  INDICATORID                      471993 non-null  float64
 30  INDICATORENG                     471993 non-null  object
 31  INDICATORFRA                     471993 non-null  object
 32  SUBINDICATORID                   471993 non-null  float64
 33  SUBINDICATORENG                  471993 non-null  object
 34  SUBINDICATORFRA                  471993 non-null  object
dtypes: float64(3), int64(7), object(25)
memory usage: 126.0+ MB

In [53]:
# dropping the french columns: descrip_F,TITLE_F ,DEPT_F ,SUBINDICATORFRA,INDICATORFRA AND SAVE IT IN A NEW datafarme call ot df_HC
df = data.drop(columns=['descrip_F', 'TITLE_F', 'DEPT_F', 'SUBINDICATORFRA', 'INDICATORFRA'])

In [54]:
# extract the df to be equal only where DEPT_E = 'Health Canada'or 'Public Service' or'Public Health Agency of Canada'
df = df[df['DEPT_E'].isin(['Health Canada', 'Public Service', 'Public Health Agency of Canada'])]
df.head()

,LEVEL1ID,LEVEL2ID,LEVEL3ID,LEVEL4ID,LEVEL5ID,SURVEYR,BYCOND,descrip_E,DEMCODE,QUESTION,TITLE_E,ANSWER1,ANSWER2,ANSWER3,ANSWER4,ANSWER5,ANSWER6,ANSWER7,MOST_POSITIVE_OR_LEAST_NEGATIVE,NEUTRAL_OR_MIDDLE_CATEGORY,MOST_NEGATIVE_OR_LEAST_POSITIVE,AGREE,SCORE5,SCORE100,ANSCOUNT,DEPT_E,INDICATORID,INDICATORENG,SUBINDICATORID,SUBINDICATORENG
0,0,0,0,0,0,2022,Q117 = 1,Man,1087,Q01,"Question 1. I have the tools, technology and e...",39,42,5,9,5,0,0,81,5,14,81,4.02,76,69605.0,Public Service,4.0,Workplace,14.0,Physical environment and equipment
6,6,0,0,0,0,2022,Q117 = 1,Man,1087,Q01,"Question 1. I have the tools, technology and e...",37,46,4,10,3,0,0,83,4,13,83,4.03,76,1715.0,Health Canada,4.0,Workplace,14.0,Physical environment and equipment
49,70,0,0,0,0,2022,Q117 = 1,Man,1087,Q01,"Question 1. I have the tools, technology and e...",40,41,5,10,4,0,0,81,5,14,81,4.04,76,530.0,Public Health Agency of Canada,4.0,Workplace,14.0,Physical environment and equipment
69,0,0,0,0,0,2020,Q117 = 1,Man,1087,Q01,"Question 1. I have the tools, technology and e...",35,45,6,11,3,0,0,81,6,14,81,3.99,75,73497.0,Public Service,4.0,Workplace,14.0,Physical environment and equipment
75,6,0,0,0,0,2020,Q117 = 1,Man,1087,Q01,"Question 1. I have the tools, technology and e...",37,46,6,9,2,0,0,83,6,11,83,4.07,77,1613.0,Health Canada,4.0,Workplace,14.0,Physical environment and equipment

In [55]:
df.shape

(22198, 30)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22198 entries, 0 to 471967
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   LEVEL1ID                         22198 non-null  int64
 1   LEVEL2ID                         22198 non-null  int64
 2   LEVEL3ID                         22198 non-null  int64
 3   LEVEL4ID                         22198 non-null  int64
 4   LEVEL5ID                         22198 non-null  int64
 5   SURVEYR                          22198 non-null  int64
 6   BYCOND                           22198 non-null  object
 7   descrip_E                        22198 non-null  object
 8   DEMCODE                          22198 non-null  int64
 9   QUESTION                         22198 non-null  object
 10  TITLE_E                          22198 non-null  object
 11  ANSWER1                          21305 non-null  object
 12  ANSWER2                          21305 non-null  object
 13  ANSWER3                          21305 non-null  object
 14  ANSWER4                          21305 non-null  object
 15  ANSWER5                          21305 non-null  object
 16  ANSWER6                          21305 non-null  object
 17  ANSWER7                          21305 non-null  object
 18  MOST_POSITIVE_OR_LEAST_NEGATIVE  21305 non-null  object
 19  NEUTRAL_OR_MIDDLE_CATEGORY       21305 non-null  object
 20  MOST_NEGATIVE_OR_LEAST_POSITIVE  21305 non-null  object
 21  AGREE                            21305 non-null  object
 22  SCORE5                           21305 non-null  object
 23  SCORE100                         21305 non-null  object
 24  ANSCOUNT                         19836 non-null  float64
 25  DEPT_E                           22198 non-null  object
 26  INDICATORID                      22198 non-null  float64
 27  INDICATORENG                     22198 non-null  object
 28  SUBINDICATORID                   22198 non-null  float64
 29  SUBINDICATORENG                  22198 non-null  object
dtypes: float64(3), int64(7), object(20)
memory usage: 5.3+ MB

In [57]:
# find the null values in the df
df.isnull().sum()

LEVEL1ID                              0
LEVEL2ID                              0
LEVEL3ID                              0
LEVEL4ID                              0
LEVEL5ID                              0
SURVEYR                               0
BYCOND                                0
descrip_E                             0
DEMCODE                               0
QUESTION                              0
TITLE_E                               0
ANSWER1                             893
ANSWER2                             893
ANSWER3                             893
ANSWER4                             893
ANSWER5                             893
ANSWER6                             893
ANSWER7                             893
MOST_POSITIVE_OR_LEAST_NEGATIVE     893
NEUTRAL_OR_MIDDLE_CATEGORY          893
MOST_NEGATIVE_OR_LEAST_POSITIVE     893
AGREE                               893
SCORE5                              893
SCORE100                            893
ANSCOUNT                           2362
DEPT_E                                0
INDICATORID                           0
INDICATORENG                          0
SUBINDICATORID                        0
SUBINDICATORENG                       0
dtype: int64

In [58]:
# records where ANSWER1 = 'X'
df[df['ANSWER3'] == 'X']

,LEVEL1ID,LEVEL2ID,LEVEL3ID,LEVEL4ID,LEVEL5ID,SURVEYR,BYCOND,descrip_E,DEMCODE,QUESTION,TITLE_E,ANSWER1,ANSWER2,ANSWER3,ANSWER4,ANSWER5,ANSWER6,ANSWER7,MOST_POSITIVE_OR_LEAST_NEGATIVE,NEUTRAL_OR_MIDDLE_CATEGORY,MOST_NEGATIVE_OR_LEAST_POSITIVE,AGREE,SCORE5,SCORE100,ANSCOUNT,DEPT_E,INDICATORID,INDICATORENG,SUBINDICATORID,SUBINDICATORENG
310,70,0,0,0,0,2022,Q117 = 3,Another gender,1089,Q01,"Question 1. I have the tools, technology and e...",X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Public Health Agency of Canada,4.0,Workplace,14.0,Physical environment and equipment
1045,6,0,0,0,0,2022,D118C = 1,"Persons with a disability, speech disability",1095,Q01,"Question 1. I have the tools, technology and e...",X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Health Canada,4.0,Workplace,14.0,Physical environment and equipment
1078,70,0,0,0,0,2022,D118C = 1,"Persons with a disability, speech disability",1095,Q01,"Question 1. I have the tools, technology and e...",X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Public Health Agency of Canada,4.0,Workplace,14.0,Physical environment and equipment
1097,6,0,0,0,0,2022,D118C = 2,"Persons with a disability, speech disability n...",1096,Q01,"Question 1. I have the tools, technology and e...",X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Health Canada,4.0,Workplace,14.0,Physical environment and equipment
1140,70,0,0,0,0,2022,D118C = 2,"Persons with a disability, speech disability n...",1096,Q01,"Question 1. I have the tools, technology and e...",X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Public Health Agency of Canada,4.0,Workplace,14.0,Physical environment and equipment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471315,6,0,0,0,0,2022,D121 = 20,"Two or more Ethnic Origins, Africa only",1147,Q55,Question 55. I would prefer to remain with my ...,X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Health Canada,1.0,Employee engagement,1.0,Employee engagement
471370,70,0,0,0,0,2022,D121 = 21,"Two or more Ethnic Origins, Asia only",1148,Q55,Question 55. I would prefer to remain with my ...,X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Public Health Agency of Canada,1.0,Employee engagement,1.0,Employee engagement
471594,6,0,0,0,0,2022,D122A = 1,2SLGBTQIA+: Two-spirit,1152,Q55,Question 55. I would prefer to remain with my ...,X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Health Canada,1.0,Employee engagement,1.0,Employee engagement
471621,70,0,0,0,0,2022,D122A = 1,2SLGBTQIA+: Two-spirit,1152,Q55,Question 55. I would prefer to remain with my ...,X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Public Health Agency of Canada,1.0,Employee engagement,1.0,Employee engagement
471879,70,0,0,0,0,2022,D122E = 1,2SLGBTQIA+: Transgender,1156,Q55,Question 55. I would prefer to remain with my ...,X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Public Health Agency of Canada,1.0,Employee engagement,1.0,Employee engagement

In [59]:
# records where ANSWER3 or ANSWER4 or ANSWER5 or ANSWER6 or ANSWER7 = '9999'
df[(df['ANSWER3'] == '9999') | (df['ANSWER4'] == '9999') |(df['ANSWER5'] == '9999') |(df['ANSWER5'] == '9999') |(df['ANSWER7'] == '9999')]

Empty DataFrame
Columns: [LEVEL1ID, LEVEL2ID, LEVEL3ID, LEVEL4ID, LEVEL5ID, SURVEYR, BYCOND, descrip_E, DEMCODE, QUESTION, TITLE_E, ANSWER1, ANSWER2, ANSWER3, ANSWER4, ANSWER5, ANSWER6, ANSWER7, MOST_POSITIVE_OR_LEAST_NEGATIVE, NEUTRAL_OR_MIDDLE_CATEGORY, MOST_NEGATIVE_OR_LEAST_POSITIVE, AGREE, SCORE5, SCORE100, ANSCOUNT, DEPT_E, INDICATORID, INDICATORENG, SUBINDICATORID, SUBINDICATORENG]
Index: []

In [60]:
# Replace and value in the dataset that equal to '9999' with NaN
df.replace([9999, '9999'], pd.NA, inplace=True)

In [61]:
# records where ANSWER3 or ANSWER4 or ANSWER5 or ANSWER6 or ANSWER7 = '9999'
df[(df['ANSWER3'] == '9999') | (df['ANSWER4'] == '9999') |(df['ANSWER5'] == '9999') |(df['ANSWER5'] == '9999') |(df['ANSWER7'] == '9999')]

Empty DataFrame
Columns: [LEVEL1ID, LEVEL2ID, LEVEL3ID, LEVEL4ID, LEVEL5ID, SURVEYR, BYCOND, descrip_E, DEMCODE, QUESTION, TITLE_E, ANSWER1, ANSWER2, ANSWER3, ANSWER4, ANSWER5, ANSWER6, ANSWER7, MOST_POSITIVE_OR_LEAST_NEGATIVE, NEUTRAL_OR_MIDDLE_CATEGORY, MOST_NEGATIVE_OR_LEAST_POSITIVE, AGREE, SCORE5, SCORE100, ANSCOUNT, DEPT_E, INDICATORID, INDICATORENG, SUBINDICATORID, SUBINDICATORENG]
Index: []

In [62]:
# Replace and value in the dataset that equal to 'X' with NaN
df = df.replace('X', pd.NA)

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22198 entries, 0 to 471967
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   LEVEL1ID                         22198 non-null  int64
 1   LEVEL2ID                         22198 non-null  int64
 2   LEVEL3ID                         22198 non-null  int64
 3   LEVEL4ID                         22198 non-null  int64
 4   LEVEL5ID                         22198 non-null  int64
 5   SURVEYR                          22198 non-null  int64
 6   BYCOND                           22198 non-null  object
 7   descrip_E                        22198 non-null  object
 8   DEMCODE                          22198 non-null  int64
 9   QUESTION                         22198 non-null  object
 10  TITLE_E                          22198 non-null  object
 11  ANSWER1                          19836 non-null  object
 12  ANSWER2                          19836 non-null  object
 13  ANSWER3                          19836 non-null  object
 14  ANSWER4                          19836 non-null  object
 15  ANSWER5                          19836 non-null  object
 16  ANSWER6                          19836 non-null  object
 17  ANSWER7                          19836 non-null  object
 18  MOST_POSITIVE_OR_LEAST_NEGATIVE  19836 non-null  object
 19  NEUTRAL_OR_MIDDLE_CATEGORY       19836 non-null  object
 20  MOST_NEGATIVE_OR_LEAST_POSITIVE  19836 non-null  object
 21  AGREE                            19836 non-null  object
 22  SCORE5                           19836 non-null  object
 23  SCORE100                         19836 non-null  object
 24  ANSCOUNT                         19836 non-null  float64
 25  DEPT_E                           22198 non-null  object
 26  INDICATORID                      22198 non-null  float64
 27  INDICATORENG                     22198 non-null  object
 28  SUBINDICATORID                   22198 non-null  float64
 29  SUBINDICATORENG                  22198 non-null  object
dtypes: float64(3), int64(7), object(20)
memory usage: 5.3+ MB

In [64]:
# Change the data type of BYCOND to object
df['BYCOND'] = df['BYCOND'].astype(object)

In [65]:
# Change the data type of DEMCODE to int
df['DEMCODE'] = df['DEMCODE'].astype('Int64')

In [66]:
answers_cols = ['ANSWER1', 'ANSWER2', 'ANSWER3', 'ANSWER4', 'ANSWER5', 'ANSWER6', 'ANSWER7']

In [67]:
df[answers_cols] = df[answers_cols].apply(pd.to_numeric, errors='coerce')

In [68]:
# Change the data type of answers columns  to integer
df[answers_cols] = df[answers_cols].astype('Int64')

In [69]:
# Select the desired columns using a list
cols_to_convert = ['MOST_POSITIVE_OR_LEAST_NEGATIVE', 'NEUTRAL_OR_MIDDLE_CATEGORY', 'MOST_NEGATIVE_OR_LEAST_POSITIVE','AGREE','SCORE5','SCORE100','ANSCOUNT']
# Apply pd.to_numeric to the selected columns
df[cols_to_convert] = df[cols_to_convert].apply(pd.to_numeric, errors='coerce')

In [70]:
# Change the data type of columns ANSWER1 and ANSWER2 to integer
df[cols_to_convert] = df[cols_to_convert].astype(pd.Int64Dtype(),errors='ignore')

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22198 entries, 0 to 471967
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   LEVEL1ID                         22198 non-null  int64
 1   LEVEL2ID                         22198 non-null  int64
 2   LEVEL3ID                         22198 non-null  int64
 3   LEVEL4ID                         22198 non-null  int64
 4   LEVEL5ID                         22198 non-null  int64
 5   SURVEYR                          22198 non-null  int64
 6   BYCOND                           22198 non-null  object
 7   descrip_E                        22198 non-null  object
 8   DEMCODE                          22198 non-null  Int64
 9   QUESTION                         22198 non-null  object
 10  TITLE_E                          22198 non-null  object
 11  ANSWER1                          19836 non-null  Int64
 12  ANSWER2                          19836 non-null  Int64
 13  ANSWER3                          19836 non-null  Int64
 14  ANSWER4                          19836 non-null  Int64
 15  ANSWER5                          19836 non-null  Int64
 16  ANSWER6                          19836 non-null  Int64
 17  ANSWER7                          19836 non-null  Int64
 18  MOST_POSITIVE_OR_LEAST_NEGATIVE  19836 non-null  Int64
 19  NEUTRAL_OR_MIDDLE_CATEGORY       19836 non-null  Int64
 20  MOST_NEGATIVE_OR_LEAST_POSITIVE  19836 non-null  Int64
 21  AGREE                            19836 non-null  Int64
 22  SCORE5                           19836 non-null  float64
 23  SCORE100                         19836 non-null  Int64
 24  ANSCOUNT                         19836 non-null  Int64
 25  DEPT_E                           22198 non-null  object
 26  INDICATORID                      22198 non-null  float64
 27  INDICATORENG                     22198 non-null  object
 28  SUBINDICATORID                   22198 non-null  float64
 29  SUBINDICATORENG                  22198 non-null  object
dtypes: Int64(14), float64(3), int64(6), object(7)
memory usage: 5.5+ MB

In [72]:
# Create new column call it SUM_ANSRS, fill it with the sum of columns ANSWER1 and ANSWER2 and ANSWER3 andANSWER4 and ANSWER5 and ANSWER6 and ANSWER7
#df['SUM_ANSRS'] = df['ANSWER1'] + df['ANSWER2'] + df['ANSWER3']+ df['ANSWER4']+ df['ANSWER4']+ df['ANSWER6']+ df['ANSWER7']

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22198 entries, 0 to 471967
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   LEVEL1ID                         22198 non-null  int64
 1   LEVEL2ID                         22198 non-null  int64
 2   LEVEL3ID                         22198 non-null  int64
 3   LEVEL4ID                         22198 non-null  int64
 4   LEVEL5ID                         22198 non-null  int64
 5   SURVEYR                          22198 non-null  int64
 6   BYCOND                           22198 non-null  object
 7   descrip_E                        22198 non-null  object
 8   DEMCODE                          22198 non-null  Int64
 9   QUESTION                         22198 non-null  object
 10  TITLE_E                          22198 non-null  object
 11  ANSWER1                          19836 non-null  Int64
 12  ANSWER2                          19836 non-null  Int64
 13  ANSWER3                          19836 non-null  Int64
 14  ANSWER4                          19836 non-null  Int64
 15  ANSWER5                          19836 non-null  Int64
 16  ANSWER6                          19836 non-null  Int64
 17  ANSWER7                          19836 non-null  Int64
 18  MOST_POSITIVE_OR_LEAST_NEGATIVE  19836 non-null  Int64
 19  NEUTRAL_OR_MIDDLE_CATEGORY       19836 non-null  Int64
 20  MOST_NEGATIVE_OR_LEAST_POSITIVE  19836 non-null  Int64
 21  AGREE                            19836 non-null  Int64
 22  SCORE5                           19836 non-null  float64
 23  SCORE100                         19836 non-null  Int64
 24  ANSCOUNT                         19836 non-null  Int64
 25  DEPT_E                           22198 non-null  object
 26  INDICATORID                      22198 non-null  float64
 27  INDICATORENG                     22198 non-null  object
 28  SUBINDICATORID                   22198 non-null  float64
 29  SUBINDICATORENG                  22198 non-null  object
dtypes: Int64(14), float64(3), int64(6), object(7)
memory usage: 5.5+ MB

In [74]:
df.head()

,LEVEL1ID,LEVEL2ID,LEVEL3ID,LEVEL4ID,LEVEL5ID,SURVEYR,BYCOND,descrip_E,DEMCODE,QUESTION,TITLE_E,ANSWER1,ANSWER2,ANSWER3,ANSWER4,ANSWER5,ANSWER6,ANSWER7,MOST_POSITIVE_OR_LEAST_NEGATIVE,NEUTRAL_OR_MIDDLE_CATEGORY,MOST_NEGATIVE_OR_LEAST_POSITIVE,AGREE,SCORE5,SCORE100,ANSCOUNT,DEPT_E,INDICATORID,INDICATORENG,SUBINDICATORID,SUBINDICATORENG
0,0,0,0,0,0,2022,Q117 = 1,Man,1087,Q01,"Question 1. I have the tools, technology and e...",39,42,5,9,5,0,0,81,5,14,81,4.02,76,69605,Public Service,4.0,Workplace,14.0,Physical environment and equipment
6,6,0,0,0,0,2022,Q117 = 1,Man,1087,Q01,"Question 1. I have the tools, technology and e...",37,46,4,10,3,0,0,83,4,13,83,4.03,76,1715,Health Canada,4.0,Workplace,14.0,Physical environment and equipment
49,70,0,0,0,0,2022,Q117 = 1,Man,1087,Q01,"Question 1. I have the tools, technology and e...",40,41,5,10,4,0,0,81,5,14,81,4.04,76,530,Public Health Agency of Canada,4.0,Workplace,14.0,Physical environment and equipment
69,0,0,0,0,0,2020,Q117 = 1,Man,1087,Q01,"Question 1. I have the tools, technology and e...",35,45,6,11,3,0,0,81,6,14,81,3.99,75,73497,Public Service,4.0,Workplace,14.0,Physical environment and equipment
75,6,0,0,0,0,2020,Q117 = 1,Man,1087,Q01,"Question 1. I have the tools, technology and e...",37,46,6,9,2,0,0,83,6,11,83,4.07,77,1613,Health Canada,4.0,Workplace,14.0,Physical environment and equipment

In [75]:
answer_cols = ["ANSWER1", "ANSWER2", "ANSWER3", "ANSWER4", "ANSWER5", "ANSWER6"]
df[answer_cols] = df[answer_cols].apply(pd.to_numeric, errors='coerce')

In [76]:

# CASE 1: If ANSWER3 is null
df.loc[df['ANSWER3'].isna(), 'MOST_POSITIVE_OR_LEAST_NEGATIVE'] = df['ANSWER1']
df.loc[df['ANSWER3'].isna(), 'MOST_NEGATIVE_OR_LEAST_POSITIVE'] = df['ANSWER2']

# CASE 2: If ANSWER3 is not null and ANSWER4 is null
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].isna(), 'MOST_POSITIVE_OR_LEAST_NEGATIVE'] = df['ANSWER1']
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].isna(), 'NEUTRAL_OR_MIDDLE_CATEGORY'] = df['ANSWER2']
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].isna(), 'MOST_NEGATIVE_OR_LEAST_POSITIVE'] = df['ANSWER3']

# CASE 3: If ANSWER3 is not null, ANSWER4 is not null, and ANSWER5 is null
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].notna() & df['ANSWER5'].isna(), 'MOST_POSITIVE_OR_LEAST_NEGATIVE'] = df['ANSWER1'] + df['ANSWER2']
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].notna() & df['ANSWER5'].isna(), 'NEUTRAL_OR_MIDDLE_CATEGORY'] = df['ANSWER3']
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].notna() & df['ANSWER5'].isna(), 'MOST_NEGATIVE_OR_LEAST_POSITIVE'] = df['ANSWER4']

# CASE 4: If ANSWER3, ANSWER4, ANSWER5 are not null, and ANSWER6 is null
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].notna() & df['ANSWER5'].notna() & df['ANSWER6'].isna(), 'MOST_POSITIVE_OR_LEAST_NEGATIVE'] = df['ANSWER1'] + df['ANSWER2']
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].notna() & df['ANSWER5'].notna() & df['ANSWER6'].isna(), 'NEUTRAL_OR_MIDDLE_CATEGORY'] = df['ANSWER3']
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].notna() & df['ANSWER5'].notna() & df['ANSWER6'].isna(), 'MOST_NEGATIVE_OR_LEAST_POSITIVE'] = df['ANSWER4']

In [77]:
df.isnull().sum()

LEVEL1ID                              0
LEVEL2ID                              0
LEVEL3ID                              0
LEVEL4ID                              0
LEVEL5ID                              0
SURVEYR                               0
BYCOND                                0
descrip_E                             0
DEMCODE                               0
QUESTION                              0
TITLE_E                               0
ANSWER1                            2362
ANSWER2                            2362
ANSWER3                            2362
ANSWER4                            2362
ANSWER5                            2362
ANSWER6                            2362
ANSWER7                            2362
MOST_POSITIVE_OR_LEAST_NEGATIVE    2362
NEUTRAL_OR_MIDDLE_CATEGORY         2362
MOST_NEGATIVE_OR_LEAST_POSITIVE    2362
AGREE                              2362
SCORE5                             2362
SCORE100                           2362
ANSCOUNT                           2362
DEPT_E                                0
INDICATORID                           0
INDICATORENG                          0
SUBINDICATORID                        0
SUBINDICATORENG                       0
dtype: int64

In [78]:
# export the dataset df_HC to a csv file and call it subset1_HealthCanada
df.to_csv('subset1_cleaned.csv', index=False)

In [79]:
# in 'QUESTION' where the Values = D56_1 change it to Q56_1
df.loc[df['QUESTION'] == 'D56_1', 'QUESTION'] = 'Q56_1'

In [80]:
# in 'QUESTION' where the Values = D56_2 change it to Q56_2
df.loc[df['QUESTION'] == 'D56_2', 'QUESTION'] = 'Q56_2'

In [81]:

# Define the columns to be set to NaN
cols_to_nullify = [
    "MOST_POSITIVE_OR_LEAST_NEGATIVE",
    "NEUTRAL_OR_MIDDLE_CATEGORY",
    "MOST_NEGATIVE_OR_LEAST_POSITIVE",
    "AGREE",
    "SCORE5",
    "SCORE100"
]

# Set the columns to NaN where QUESTIONS that doesnt have sentiment asnwers
df.loc[df['QUESTION'].isin(['Q56_1', 'Q56_2', 'Q81', 'Q83', 'Q93', 'Q95']), cols_to_nullify] = pd.NA

In [82]:
# Set the values where QUESTION is 'Q88'
df.loc[df['QUESTION'] == 'Q88', 'MOST_POSITIVE_OR_LEAST_NEGATIVE'] = df['ANSWER2']
df.loc[df['QUESTION'] == 'Q88', 'MOST_NEGATIVE_OR_LEAST_POSITIVE'] = df['ANSWER1']
df.loc[df['QUESTION'] == 'Q88', 'NEUTRAL_OR_MIDDLE_CATEGORY'] = df['ANSWER3'] + df['ANSWER4']

In [83]:
import re

# Define the pattern to match questions like Q57, Q58, Q59, etc., including any suffix (e.g., Q58a, Q58b, etc.)
questions_pattern = r'Q(57|58|59|60|61|64|65|67|68)[a-zA-Z]?'

# Set the values where QUESTION matches the pattern
df.loc[df['QUESTION'].str.match(questions_pattern), 'MOST_POSITIVE_OR_LEAST_NEGATIVE'] = df['ANSWER2']
df.loc[df['QUESTION'].str.match(questions_pattern), 'MOST_NEGATIVE_OR_LEAST_POSITIVE'] = df['ANSWER1']

In [84]:
# export the dataset df_HC to a csv file and call it subset1_HealthCanada
df.to_csv('subset3_cleaned.csv', index=False)