In [ ]:
import pandas as pd

In [ ]:
# Import the data
data = pd.read_csv('Subset 5 - 2022_2023 PSES open dataset - with labels_Sous-ensemble 5 - Ensemble de données ouvertes du SAFF de 2022_23.csv', encoding='latin-1')

In [ ]:
data.shape

(129038, 35)

In [ ]:
# show head of the data, and show all the columns
pd.set_option('display.max_columns', None)
data.head()

,LEVEL1ID,LEVEL2ID,LEVEL3ID,LEVEL4ID,LEVEL5ID,SURVEYR,BYCOND,descrip_E,descrip_F,DEMCODE,QUESTION,TITLE_E,TITLE_F,ANSWER1,ANSWER2,ANSWER3,ANSWER4,ANSWER5,ANSWER6,ANSWER7,MOST_POSITIVE_OR_LEAST_NEGATIVE,NEUTRAL_OR_MIDDLE_CATEGORY,MOST_NEGATIVE_OR_LEAST_POSITIVE,AGREE,SCORE5,SCORE100,ANSCOUNT,DEPT_E,DEPT_F,INDICATORID,INDICATORENG,INDICATORFRA,SUBINDICATORID,SUBINDICATORENG,SUBINDICATORFRA
0,0,0,0,0,0,2022,Q93 = 1,Working on-site,Travaille sur place,1000.0,Q01,"Question 1. I have the tools, technology and e...","Question 1. Je dispose des outils, de la techn...",28,44,6,14,8,0,0,72,6,23,72,3.68,67,25685.0,Public Service,Fonction publique,4.0,Workplace,Milieu de travail,14.0,Physical environment and equipment,Environnement physique et équipement
1,1,0,0,0,0,2022,Q93 = 1,Working on-site,Travaille sur place,1000.0,Q01,"Question 1. I have the tools, technology and e...","Question 1. Je dispose des outils, de la techn...",52,40,3,4,1,0,0,92,3,5,92,4.37,84,1415.0,Canada Revenue Agency,Agence du revenu du Canada,4.0,Workplace,Milieu de travail,14.0,Physical environment and equipment,Environnement physique et équipement
2,2,0,0,0,0,2022,Q93 = 1,Working on-site,Travaille sur place,1000.0,Q01,"Question 1. I have the tools, technology and e...","Question 1. Je dispose des outils, de la techn...",42,41,5,9,4,0,0,83,5,12,83,4.08,77,1980.0,Employment and Social Development Canada,Emploi et Développement social Canada,4.0,Workplace,Milieu de travail,14.0,Physical environment and equipment,Environnement physique et équipement
3,3,0,0,0,0,2022,Q93 = 1,Working on-site,Travaille sur place,1000.0,Q01,"Question 1. I have the tools, technology and e...","Question 1. Je dispose des outils, de la techn...",26,44,7,15,8,0,0,70,7,23,70,3.64,66,4595.0,Department of National Defence,Ministère de la Défense nationale,4.0,Workplace,Milieu de travail,14.0,Physical environment and equipment,Environnement physique et équipement
4,4,0,0,0,0,2022,Q93 = 1,Working on-site,Travaille sur place,1000.0,Q01,"Question 1. I have the tools, technology and e...","Question 1. Je dispose des outils, de la techn...",16,46,7,18,13,0,0,62,7,31,62,3.34,59,3425.0,Correctional Service Canada,Service correctionnel Canada,4.0,Workplace,Milieu de travail,14.0,Physical environment and equipment,Environnement physique et équipement

In [ ]:
data.tail()

,LEVEL1ID,LEVEL2ID,LEVEL3ID,LEVEL4ID,LEVEL5ID,SURVEYR,BYCOND,descrip_E,descrip_F,DEMCODE,QUESTION,TITLE_E,TITLE_F,ANSWER1,ANSWER2,ANSWER3,ANSWER4,ANSWER5,ANSWER6,ANSWER7,MOST_POSITIVE_OR_LEAST_NEGATIVE,NEUTRAL_OR_MIDDLE_CATEGORY,MOST_NEGATIVE_OR_LEAST_POSITIVE,AGREE,SCORE5,SCORE100,ANSCOUNT,DEPT_E,DEPT_F,INDICATORID,INDICATORENG,INDICATORFRA,SUBINDICATORID,SUBINDICATORENG,SUBINDICATORFRA
129033,33,0,0,0,0,2018,Q104 = 7,Governor-in-council appointee,Nomination par le gouverneur en conseil,1015.0,Q15,Question 15. I have support at work to provide...,"Question 15. Au travail, j'obtiens du soutien ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canadian Space Agency,Agence spatiale canadienne,3.0,Workforce,Effectif,6.0,Empowerment,Habilitation
129034,36,0,0,0,0,2018,Q104 = 7,Governor-in-council appointee,Nomination par le gouverneur en conseil,1015.0,Q15,Question 15. I have support at work to provide...,"Question 15. Au travail, j'obtiens du soutien ...",55,35,5,5,0,0,0,90,5,5,90,4.4,85,20.0,Parole Board of Canada,Commission des libérations conditionnelles du ...,3.0,Workforce,Effectif,6.0,Empowerment,Habilitation
129035,39,0,0,0,0,2018,Q104 = 7,Governor-in-council appointee,Nomination par le gouverneur en conseil,1015.0,Q15,Question 15. I have support at work to provide...,"Question 15. Au travail, j'obtiens du soutien ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transportation Safety Board of Canada,Bureau de la sécurité des transports du Canada,3.0,Workforce,Effectif,6.0,Empowerment,Habilitation
129036,41,0,0,0,0,2018,Q104 = 7,Governor-in-council appointee,Nomination par le gouverneur en conseil,1015.0,Q15,Question 15. I have support at work to provide...,"Question 15. Au travail, j'obtiens du soutien ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canadian Human Rights Commission,Commission canadienne des droits de la personne,3.0,Workforce,Effectif,6.0,Empowerment,Habilitation
129037,46,0,0,0,0,2018,Q104 = 7,Governo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129038 entries, 0 to 129037
Data columns (total 35 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   LEVEL1ID                         129038 non-null  int64
 1   LEVEL2ID                         129038 non-null  int64
 2   LEVEL3ID                         129038 non-null  int64
 3   LEVEL4ID                         129038 non-null  int64
 4   LEVEL5ID                         129038 non-null  int64
 5   SURVEYR                          129038 non-null  int64
 6   BYCOND                           129038 non-null  object
 7   descrip_E                        129038 non-null  object
 8   descrip_F                        129037 non-null  object
 9   DEMCODE                          129037 non-null  float64
 10  QUESTION                         129037 non-null  object
 11  TITLE_E                          129037 non-null  object
 12  TITLE_F                          129037 non-null  object
 13  ANSWER1                          102152 non-null  object
 14  ANSWER2                          102152 non-null  object
 15  ANSWER3                          102152 non-null  object
 16  ANSWER4                          102152 non-null  object
 17  ANSWER5                          102152 non-null  object
 18  ANSWER6                          102152 non-null  object
 19  ANSWER7                          102152 non-null  object
 20  MOST_POSITIVE_OR_LEAST_NEGATIVE  102152 non-null  object
 21  NEUTRAL_OR_MIDDLE_CATEGORY       102152 non-null  object
 22  MOST_NEGATIVE_OR_LEAST_POSITIVE  102152 non-null  object
 23  AGREE                            102152 non-null  object
 24  SCORE5                           102152 non-null  object
 25  SCORE100                         102152 non-null  object
 26  ANSCOUNT                         91467 non-null   float64
 27  DEPT_E                           129037 non-null  object
 28  DEPT_F                           129037 non-null  object
 29  INDICATORID                      129037 non-null  float64
 30  INDICATORENG                     129037 non-null  object
 31  INDICATORFRA                     129037 non-null  object
 32  SUBINDICATORID                   129037 non-null  float64
 33  SUBINDICATORENG                  129037 non-null  object
 34  SUBINDICATORFRA                  129037 non-null  object
dtypes: float64(4), int64(6), object(25)
memory usage: 34.5+ MB

In [ ]:
# dropping the french columns: descrip_F,TITLE_F ,DEPT_F ,SUBINDICATORFRA,INDICATORFRA AND SAVE IT IN A NEW datafarme call ot df_HC
df = data.drop(columns=['descrip_F', 'TITLE_F', 'DEPT_F', 'SUBINDICATORFRA', 'INDICATORFRA'])

In [ ]:
# extract the df to be equal only where DEPT_E = 'Health Canada'or 'Public Service' or'Public Health Agency of Canada'
df = df[df['DEPT_E'].isin(['Health Canada', 'Public Service', 'Public Health Agency of Canada'])]
df.head()

,LEVEL1ID,LEVEL2ID,LEVEL3ID,LEVEL4ID,LEVEL5ID,SURVEYR,BYCOND,descrip_E,DEMCODE,QUESTION,TITLE_E,ANSWER1,ANSWER2,ANSWER3,ANSWER4,ANSWER5,ANSWER6,ANSWER7,MOST_POSITIVE_OR_LEAST_NEGATIVE,NEUTRAL_OR_MIDDLE_CATEGORY,MOST_NEGATIVE_OR_LEAST_POSITIVE,AGREE,SCORE5,SCORE100,ANSCOUNT,DEPT_E,INDICATORID,INDICATORENG,SUBINDICATORID,SUBINDICATORENG
0,0,0,0,0,0,2022,Q93 = 1,Working on-site,1000.0,Q01,"Question 1. I have the tools, technology and e...",28,44,6,14,8,0,0,72,6,23,72,3.68,67,25685.0,Public Service,4.0,Workplace,14.0,Physical environment and equipment
6,6,0,0,0,0,2022,Q93 = 1,Working on-site,1000.0,Q01,"Question 1. I have the tools, technology and e...",37,47,3,8,5,0,0,84,3,13,84,4.03,76,260.0,Health Canada,4.0,Workplace,14.0,Physical environment and equipment
48,70,0,0,0,0,2022,Q93 = 1,Working on-site,1000.0,Q01,"Question 1. I have the tools, technology and e...",42,42,4,9,4,0,0,83,4,13,83,4.09,77,230.0,Public Health Agency of Canada,4.0,Workplace,14.0,Physical environment and equipment
68,0,0,0,0,0,2020,Q93 = 1,Working on-site,1000.0,Q01,"Question 1. I have the tools, technology and e...",31,44,7,13,5,0,0,75,7,18,75,3.83,71,21444.0,Public Service,4.0,Workplace,14.0,Physical environment and equipment
74,6,0,0,0,0,2020,Q93 = 1,Working on-site,1000.0,Q01,"Question 1. I have the tools, technology and e...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Health Canada,4.0,Workplace,14.0,Physical environment and equipment

In [ ]:
df.shape

(6381, 30)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6381 entries, 0 to 129012
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   LEVEL1ID                         6381 non-null   int64
 1   LEVEL2ID                         6381 non-null   int64
 2   LEVEL3ID                         6381 non-null   int64
 3   LEVEL4ID                         6381 non-null   int64
 4   LEVEL5ID                         6381 non-null   int64
 5   SURVEYR                          6381 non-null   int64
 6   BYCOND                           6381 non-null   object
 7   descrip_E                        6381 non-null   object
 8   DEMCODE                          6381 non-null   float64
 9   QUESTION                         6381 non-null   object
 10  TITLE_E                          6381 non-null   object
 11  ANSWER1                          6004 non-null   object
 12  ANSWER2                          6004 non-null   object
 13  ANSWER3                          6004 non-null   object
 14  ANSWER4                          6004 non-null   object
 15  ANSWER5                          6004 non-null   object
 16  ANSWER6                          6004 non-null   object
 17  ANSWER7                          6004 non-null   object
 18  MOST_POSITIVE_OR_LEAST_NEGATIVE  6004 non-null   object
 19  NEUTRAL_OR_MIDDLE_CATEGORY       6004 non-null   object
 20  MOST_NEGATIVE_OR_LEAST_POSITIVE  6004 non-null   object
 21  AGREE                            6004 non-null   object
 22  SCORE5                           6004 non-null   object
 23  SCORE100                         6004 non-null   object
 24  ANSCOUNT                         5891 non-null   float64
 25  DEPT_E                           6381 non-null   object
 26  INDICATORID                      6381 non-null   float64
 27  INDICATORENG                     6381 non-null   object
 28  SUBINDICATORID                   6381 non-null   float64
 29  SUBINDICATORENG                  6381 non-null   object
dtypes: float64(4), int64(6), object(20)
memory usage: 1.5+ MB

In [ ]:
# find the null values in the df
df.isnull().sum()

LEVEL1ID                             0
LEVEL2ID                             0
LEVEL3ID                             0
LEVEL4ID                             0
LEVEL5ID                             0
SURVEYR                              0
BYCOND                               0
descrip_E                            0
DEMCODE                              0
QUESTION                             0
TITLE_E                              0
ANSWER1                            377
ANSWER2                            377
ANSWER3                            377
ANSWER4                            377
ANSWER5                            377
ANSWER6                            377
ANSWER7                            377
MOST_POSITIVE_OR_LEAST_NEGATIVE    377
NEUTRAL_OR_MIDDLE_CATEGORY         377
MOST_NEGATIVE_OR_LEAST_POSITIVE    377
AGREE                              377
SCORE5                             377
SCORE100                           377
ANSCOUNT                           490
DEPT_E                               0
INDICATORID                          0
INDICATORENG                         0
SUBINDICATORID                       0
SUBINDICATORENG                      0
dtype: int64

In [ ]:
# records where ANSWER1 = 'X'
df[df['ANSWER3'] == 'X']

,LEVEL1ID,LEVEL2ID,LEVEL3ID,LEVEL4ID,LEVEL5ID,SURVEYR,BYCOND,descrip_E,DEMCODE,QUESTION,TITLE_E,ANSWER1,ANSWER2,ANSWER3,ANSWER4,ANSWER5,ANSWER6,ANSWER7,MOST_POSITIVE_OR_LEAST_NEGATIVE,NEUTRAL_OR_MIDDLE_CATEGORY,MOST_NEGATIVE_OR_LEAST_POSITIVE,AGREE,SCORE5,SCORE100,ANSCOUNT,DEPT_E,INDICATORID,INDICATORENG,SUBINDICATORID,SUBINDICATORENG
1510,70,0,0,0,0,2022,Q104 = 7,Governor-in-council appointee,1015.0,Q01,"Question 1. I have the tools, technology and e...",X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Public Health Agency of Canada,4.0,Workplace,14.0,Physical environment and equipment
2126,70,0,0,0,0,2022,Q109 = 6,Access to information and privacy,1026.0,Q01,"Question 1. I have the tools, technology and e...",X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Public Health Agency of Canada,4.0,Workplace,14.0,Physical environment and equipment
2253,70,0,0,0,0,2022,Q109 = 7,Security,1027.0,Q01,"Question 1. I have the tools, technology and e...",X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Public Health Agency of Canada,4.0,Workplace,14.0,Physical environment and equipment
2452,6,0,0,0,0,2022,Q109 = 9,Library services,1029.0,Q01,"Question 1. I have the tools, technology and e...",X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Health Canada,4.0,Workplace,14.0,Physical environment and equipment
2483,70,0,0,0,0,2022,Q109 = 9,Library services,1029.0,Q01,"Question 1. I have the tools, technology and e...",X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Public Health Agency of Canada,4.0,Workplace,14.0,Physical environment and equipment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120861,70,0,0,0,0,2022,Q109 = 9,Library services,1029.0,Q14,Question 14. I am encouraged to be innovative ...,X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Public Health Agency of Canada,3.0,Workforce,6.0,Empowerment
121050,70,0,0,0,0,2022,Q109 = 10,Legal services,1030.0,Q14,Question 14. I am encouraged to be innovative ...,X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Public Health Agency of Canada,3.0,Workforce,6.0,Empowerment
122299,70,0,0,0,0,2022,Q109 = 15,Real property,1035.0,Q14,Question 14. I am encouraged to be innovative ...,X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Public Health Agency of Canada,3.0,Workforce,6.0,Empowerment
126119,6,0,0,0,0,2022,D105 = 6,Operational,1989.0,Q14,Question 14. I am encouraged to be innovative ...,X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Health Canada,3.0,Workforce,6.0,Empowerment
128966,70,0,0,0,0,2022,Q104 = 7,Governor-in-council appointee,1015.0,Q15,Question 15. I have support at work to provide...,X,X,X,X,X,X,X,X,X,X,X,X,X,NaN,Public Health Agency of Canada,3.0,Workforce,6.0,Empowerment

In [ ]:
# records where ANSWER3 or ANSWER4 or ANSWER5 or ANSWER6 or ANSWER7 = '9999'
df[(df['ANSWER3'] == '9999') | (df['ANSWER4'] == '9999') |(df['ANSWER5'] == '9999') |(df['ANSWER5'] == '9999') |(df['ANSWER7'] == '9999')]

Empty DataFrame
Columns: [LEVEL1ID, LEVEL2ID, LEVEL3ID, LEVEL4ID, LEVEL5ID, SURVEYR, BYCOND, descrip_E, DEMCODE, QUESTION, TITLE_E, ANSWER1, ANSWER2, ANSWER3, ANSWER4, ANSWER5, ANSWER6, ANSWER7, MOST_POSITIVE_OR_LEAST_NEGATIVE, NEUTRAL_OR_MIDDLE_CATEGORY, MOST_NEGATIVE_OR_LEAST_POSITIVE, AGREE, SCORE5, SCORE100, ANSCOUNT, DEPT_E, INDICATORID, INDICATORENG, SUBINDICATORID, SUBINDICATORENG]
Index: []

In [ ]:
# Replace and value in the dataset that equal to '9999' with NaN
df.replace([9999, '9999'], pd.NA, inplace=True)

In [ ]:
# records where ANSWER3 or ANSWER4 or ANSWER5 or ANSWER6 or ANSWER7 = '9999'
df[(df['ANSWER3'] == '9999') | (df['ANSWER4'] == '9999') |(df['ANSWER5'] == '9999') |(df['ANSWER5'] == '9999') |(df['ANSWER7'] == '9999')]

Empty DataFrame
Columns: [LEVEL1ID, LEVEL2ID, LEVEL3ID, LEVEL4ID, LEVEL5ID, SURVEYR, BYCOND, descrip_E, DEMCODE, QUESTION, TITLE_E, ANSWER1, ANSWER2, ANSWER3, ANSWER4, ANSWER5, ANSWER6, ANSWER7, MOST_POSITIVE_OR_LEAST_NEGATIVE, NEUTRAL_OR_MIDDLE_CATEGORY, MOST_NEGATIVE_OR_LEAST_POSITIVE, AGREE, SCORE5, SCORE100, ANSCOUNT, DEPT_E, INDICATORID, INDICATORENG, SUBINDICATORID, SUBINDICATORENG]
Index: []

In [ ]:
# Replace and value in the dataset that equal to 'X' with NaN
df = df.replace('X', pd.NA)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6381 entries, 0 to 129012
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   LEVEL1ID                         6381 non-null   int64
 1   LEVEL2ID                         6381 non-null   int64
 2   LEVEL3ID                         6381 non-null   int64
 3   LEVEL4ID                         6381 non-null   int64
 4   LEVEL5ID                         6381 non-null   int64
 5   SURVEYR                          6381 non-null   int64
 6   BYCOND                           6381 non-null   object
 7   descrip_E                        6381 non-null   object
 8   DEMCODE                          6381 non-null   float64
 9   QUESTION                         6381 non-null   object
 10  TITLE_E                          6381 non-null   object
 11  ANSWER1                          5891 non-null   object
 12  ANSWER2                          5891 non-null   object
 13  ANSWER3                          5891 non-null   object
 14  ANSWER4                          5891 non-null   object
 15  ANSWER5                          5891 non-null   object
 16  ANSWER6                          5891 non-null   object
 17  ANSWER7                          5891 non-null   object
 18  MOST_POSITIVE_OR_LEAST_NEGATIVE  5891 non-null   object
 19  NEUTRAL_OR_MIDDLE_CATEGORY       5891 non-null   object
 20  MOST_NEGATIVE_OR_LEAST_POSITIVE  5891 non-null   object
 21  AGREE                            5891 non-null   object
 22  SCORE5                           5891 non-null   object
 23  SCORE100                         5891 non-null   object
 24  ANSCOUNT                         5891 non-null   float64
 25  DEPT_E                           6381 non-null   object
 26  INDICATORID                      6381 non-null   float64
 27  INDICATORENG                     6381 non-null   object
 28  SUBINDICATORID                   6381 non-null   float64
 29  SUBINDICATORENG                  6381 non-null   object
dtypes: float64(4), int64(6), object(20)
memory usage: 1.5+ MB

In [ ]:
# Change the data type of BYCOND to object
df['BYCOND'] = df['BYCOND'].astype(object)

In [ ]:
# Change the data type of DEMCODE to int
df['DEMCODE'] = df['DEMCODE'].astype('Int64')

In [ ]:
answers_cols = ['ANSWER1', 'ANSWER2', 'ANSWER3', 'ANSWER4', 'ANSWER5', 'ANSWER6', 'ANSWER7']

In [ ]:
df[answers_cols] = df[answers_cols].apply(pd.to_numeric, errors='coerce')

In [ ]:
# Change the data type of answers columns  to integer
df[answers_cols] = df[answers_cols].astype('Int64')

In [ ]:
# Select the desired columns using a list
cols_to_convert = ['MOST_POSITIVE_OR_LEAST_NEGATIVE', 'NEUTRAL_OR_MIDDLE_CATEGORY', 'MOST_NEGATIVE_OR_LEAST_POSITIVE','AGREE','SCORE5','SCORE100','ANSCOUNT']
# Apply pd.to_numeric to the selected columns
df[cols_to_convert] = df[cols_to_convert].apply(pd.to_numeric, errors='coerce')

In [ ]:
# Change the data type of columns ANSWER1 and ANSWER2 to integer
df[cols_to_convert] = df[cols_to_convert].astype(pd.Int64Dtype(),errors='ignore')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6381 entries, 0 to 129012
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   LEVEL1ID                         6381 non-null   int64
 1   LEVEL2ID                         6381 non-null   int64
 2   LEVEL3ID                         6381 non-null   int64
 3   LEVEL4ID                         6381 non-null   int64
 4   LEVEL5ID                         6381 non-null   int64
 5   SURVEYR                          6381 non-null   int64
 6   BYCOND                           6381 non-null   object
 7   descrip_E                        6381 non-null   object
 8   DEMCODE                          6381 non-null   Int64
 9   QUESTION                         6381 non-null   object
 10  TITLE_E                          6381 non-null   object
 11  ANSWER1                          5891 non-null   Int64
 12  ANSWER2                          5891 non-null   Int64
 13  ANSWER3                          5891 non-null   Int64
 14  ANSWER4                          5891 non-null   Int64
 15  ANSWER5                          5891 non-null   Int64
 16  ANSWER6                          5891 non-null   Int64
 17  ANSWER7                          5891 non-null   Int64
 18  MOST_POSITIVE_OR_LEAST_NEGATIVE  5891 non-null   Int64
 19  NEUTRAL_OR_MIDDLE_CATEGORY       5891 non-null   Int64
 20  MOST_NEGATIVE_OR_LEAST_POSITIVE  5891 non-null   Int64
 21  AGREE                            5891 non-null   Int64
 22  SCORE5                           5891 non-null   float64
 23  SCORE100                         5891 non-null   Int64
 24  ANSCOUNT                         5891 non-null   Int64
 25  DEPT_E                           6381 non-null   object
 26  INDICATORID                      6381 non-null   float64
 27  INDICATORENG                     6381 non-null   object
 28  SUBINDICATORID                   6381 non-null   float64
 29  SUBINDICATORENG                  6381 non-null   object
dtypes: Int64(14), float64(3), int64(6), object(7)
memory usage: 1.6+ MB

In [ ]:
# Create new column call it SUM_ANSRS, fill it with the sum of columns ANSWER1 and ANSWER2 and ANSWER3 andANSWER4 and ANSWER5 and ANSWER6 and ANSWER7
#df['SUM_ANSRS'] = df['ANSWER1'] + df['ANSWER2'] + df['ANSWER3']+ df['ANSWER4']+ df['ANSWER4']+ df['ANSWER6']+ df['ANSWER7']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6381 entries, 0 to 129012
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   LEVEL1ID                         6381 non-null   int64
 1   LEVEL2ID                         6381 non-null   int64
 2   LEVEL3ID                         6381 non-null   int64
 3   LEVEL4ID                         6381 non-null   int64
 4   LEVEL5ID                         6381 non-null   int64
 5   SURVEYR                          6381 non-null   int64
 6   BYCOND                           6381 non-null   object
 7   descrip_E                        6381 non-null   object
 8   DEMCODE                          6381 non-null   Int64
 9   QUESTION                         6381 non-null   object
 10  TITLE_E                          6381 non-null   object
 11  ANSWER1                          5891 non-null   Int64
 12  ANSWER2                          5891 non-null   Int64
 13  ANSWER3                          5891 non-null   Int64
 14  ANSWER4                          5891 non-null   Int64
 15  ANSWER5                          5891 non-null   Int64
 16  ANSWER6                          5891 non-null   Int64
 17  ANSWER7                          5891 non-null   Int64
 18  MOST_POSITIVE_OR_LEAST_NEGATIVE  5891 non-null   Int64
 19  NEUTRAL_OR_MIDDLE_CATEGORY       5891 non-null   Int64
 20  MOST_NEGATIVE_OR_LEAST_POSITIVE  5891 non-null   Int64
 21  AGREE                            5891 non-null   Int64
 22  SCORE5                           5891 non-null   float64
 23  SCORE100                         5891 non-null   Int64
 24  ANSCOUNT                         5891 non-null   Int64
 25  DEPT_E                           6381 non-null   object
 26  INDICATORID                      6381 non-null   float64
 27  INDICATORENG                     6381 non-null   object
 28  SUBINDICATORID                   6381 non-null   float64
 29  SUBINDICATORENG                  6381 non-null   object
dtypes: Int64(14), float64(3), int64(6), object(7)
memory usage: 1.6+ MB

In [ ]:
df.head()

,LEVEL1ID,LEVEL2ID,LEVEL3ID,LEVEL4ID,LEVEL5ID,SURVEYR,BYCOND,descrip_E,DEMCODE,QUESTION,TITLE_E,ANSWER1,ANSWER2,ANSWER3,ANSWER4,ANSWER5,ANSWER6,ANSWER7,MOST_POSITIVE_OR_LEAST_NEGATIVE,NEUTRAL_OR_MIDDLE_CATEGORY,MOST_NEGATIVE_OR_LEAST_POSITIVE,AGREE,SCORE5,SCORE100,ANSCOUNT,DEPT_E,INDICATORID,INDICATORENG,SUBINDICATORID,SUBINDICATORENG
0,0,0,0,0,0,2022,Q93 = 1,Working on-site,1000,Q01,"Question 1. I have the tools, technology and e...",28,44,6,14,8,0,0,72,6,23,72,3.68,67,25685,Public Service,4.0,Workplace,14.0,Physical environment and equipment
6,6,0,0,0,0,2022,Q93 = 1,Working on-site,1000,Q01,"Question 1. I have the tools, technology and e...",37,47,3,8,5,0,0,84,3,13,84,4.03,76,260,Health Canada,4.0,Workplace,14.0,Physical environment and equipment
48,70,0,0,0,0,2022,Q93 = 1,Working on-site,1000,Q01,"Question 1. I have the tools, technology and e...",42,42,4,9,4,0,0,83,4,13,83,4.09,77,230,Public Health Agency of Canada,4.0,Workplace,14.0,Physical environment and equipment
68,0,0,0,0,0,2020,Q93 = 1,Working on-site,1000,Q01,"Question 1. I have the tools, technology and e...",31,44,7,13,5,0,0,75,7,18,75,3.83,71,21444,Public Service,4.0,Workplace,14.0,Physical environment and equipment
74,6,0,0,0,0,2020,Q93 = 1,Working on-site,1000,Q01,"Question 1. I have the tools, technology and e...",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,Health Canada,4.0,Workplace,14.0,Physical environment and equipment

In [ ]:
answer_cols = ["ANSWER1", "ANSWER2", "ANSWER3", "ANSWER4", "ANSWER5", "ANSWER6"]
df[answer_cols] = df[answer_cols].apply(pd.to_numeric, errors='coerce')

In [ ]:

# CASE 1: If ANSWER3 is null
df.loc[df['ANSWER3'].isna(), 'MOST_POSITIVE_OR_LEAST_NEGATIVE'] = df['ANSWER1']
df.loc[df['ANSWER3'].isna(), 'MOST_NEGATIVE_OR_LEAST_POSITIVE'] = df['ANSWER2']

# CASE 2: If ANSWER3 is not null and ANSWER4 is null
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].isna(), 'MOST_POSITIVE_OR_LEAST_NEGATIVE'] = df['ANSWER1']
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].isna(), 'NEUTRAL_OR_MIDDLE_CATEGORY'] = df['ANSWER2']
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].isna(), 'MOST_NEGATIVE_OR_LEAST_POSITIVE'] = df['ANSWER3']

# CASE 3: If ANSWER3 is not null, ANSWER4 is not null, and ANSWER5 is null
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].notna() & df['ANSWER5'].isna(), 'MOST_POSITIVE_OR_LEAST_NEGATIVE'] = df['ANSWER1'] + df['ANSWER2']
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].notna() & df['ANSWER5'].isna(), 'NEUTRAL_OR_MIDDLE_CATEGORY'] = df['ANSWER3']
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].notna() & df['ANSWER5'].isna(), 'MOST_NEGATIVE_OR_LEAST_POSITIVE'] = df['ANSWER4']

# CASE 4: If ANSWER3, ANSWER4, ANSWER5 are not null, and ANSWER6 is null
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].notna() & df['ANSWER5'].notna() & df['ANSWER6'].isna(), 'MOST_POSITIVE_OR_LEAST_NEGATIVE'] = df['ANSWER1'] + df['ANSWER2']
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].notna() & df['ANSWER5'].notna() & df['ANSWER6'].isna(), 'NEUTRAL_OR_MIDDLE_CATEGORY'] = df['ANSWER3']
df.loc[df['ANSWER3'].notna() & df['ANSWER4'].notna() & df['ANSWER5'].notna() & df['ANSWER6'].isna(), 'MOST_NEGATIVE_OR_LEAST_POSITIVE'] = df['ANSWER4']

In [ ]:
df.isnull().sum()

LEVEL1ID                             0
LEVEL2ID                             0
LEVEL3ID                             0
LEVEL4ID                             0
LEVEL5ID                             0
SURVEYR                              0
BYCOND                               0
descrip_E                            0
DEMCODE                              0
QUESTION                             0
TITLE_E                              0
ANSWER1                            490
ANSWER2                            490
ANSWER3                            490
ANSWER4                            490
ANSWER5                            490
ANSWER6                            490
ANSWER7                            490
MOST_POSITIVE_OR_LEAST_NEGATIVE    490
NEUTRAL_OR_MIDDLE_CATEGORY         490
MOST_NEGATIVE_OR_LEAST_POSITIVE    490
AGREE                              490
SCORE5                             490
SCORE100                           490
ANSCOUNT                           490
DEPT_E                               0
INDICATORID                          0
INDICATORENG                         0
SUBINDICATORID                       0
SUBINDICATORENG                      0
dtype: int64

In [ ]:
# export the dataset df_HC to a csv file and call it subset1_HealthCanada
df.to_csv('subset1_cleaned.csv', index=False)

In [ ]:
# in 'QUESTION' where the Values = D56_1 change it to Q56_1
df.loc[df['QUESTION'] == 'D56_1', 'QUESTION'] = 'Q56_1'

In [ ]:
# in 'QUESTION' where the Values = D56_2 change it to Q56_2
df.loc[df['QUESTION'] == 'D56_2', 'QUESTION'] = 'Q56_2'

In [ ]:

# Define the columns to be set to NaN
cols_to_nullify = [
    "MOST_POSITIVE_OR_LEAST_NEGATIVE",
    "NEUTRAL_OR_MIDDLE_CATEGORY",
    "MOST_NEGATIVE_OR_LEAST_POSITIVE",
    "AGREE",
    "SCORE5",
    "SCORE100"
]

# Set the columns to NaN where QUESTIONS that doesnt have sentiment asnwers
df.loc[df['QUESTION'].isin(['Q56_1', 'Q56_2', 'Q81', 'Q83', 'Q93', 'Q95']), cols_to_nullify] = pd.NA

In [ ]:
# Set the values where QUESTION is 'Q88'
df.loc[df['QUESTION'] == 'Q88', 'MOST_POSITIVE_OR_LEAST_NEGATIVE'] = df['ANSWER2']
df.loc[df['QUESTION'] == 'Q88', 'MOST_NEGATIVE_OR_LEAST_POSITIVE'] = df['ANSWER1']
df.loc[df['QUESTION'] == 'Q88', 'NEUTRAL_OR_MIDDLE_CATEGORY'] = df['ANSWER3'] + df['ANSWER4']

In [ ]:
import re

# Define the pattern to match questions like Q57, Q58, Q59, etc., including any suffix (e.g., Q58a, Q58b, etc.)
questions_pattern = r'Q(57|58|59|60|61|64|65|67|68)[a-zA-Z]?'

# Set the values where QUESTION matches the pattern
df.loc[df['QUESTION'].str.match(questions_pattern), 'MOST_POSITIVE_OR_LEAST_NEGATIVE'] = df['ANSWER2']
df.loc[df['QUESTION'].str.match(questions_pattern), 'MOST_NEGATIVE_OR_LEAST_POSITIVE'] = df['ANSWER1']

In [ ]:
# export the dataset df_HC to a csv file and call it subset1_HealthCanada
df.to_csv('subset5_cleaned.csv', index=False)